version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: ./docker/python
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
