# Generated by Django 3.2 on 2021-04-28 13:36

from django.db import migrations
from datetime import date, timedelta


def create_data(apps, schema_editor):
    course = apps.get_model('courses', 'Course')
    course(
        name='Test course',
        start_date=date.today() - timedelta(1),
        end_date=date.today() + timedelta(1),
        lectures_quantity=2
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
